name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0,10,20,30,40,50 * * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          config_timezone: Asia/Seoul,
          token: ${{ secrets.METRICS_TOKEN }}
